<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Stata – Statistical inference  with weights and survey design variables</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09_References.html" rel="next">
<link href="./06_SPSS.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f410b66b4933f15108f8fa93e83e019d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="ukds_long.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_R.html">5. Exercises</a></li><li class="breadcrumb-item"><a href="./07_Stata.html">Stata</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="https://ukdataservice.ac.uk" class="sidebar-logo-link">
      <img src="./pics/UKDS_Logos_Col_Grey_300dpi.png" alt="UKDS homepage" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./pics/UKDS_Logos_Col_Grey_300dpi.png" alt="UKDS homepage" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of Survey Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Design-Based_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Design-Based Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Real_world.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Real world population inference: things to keep in mind</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Statistical_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical Inference from Survey Data in Practice</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">5. Exercises</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_SPSS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SPSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Stata.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Stata</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix: Study-specific weighting and sample design information</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#identifying-the-survey-design-and-variables" id="toc-identifying-the-survey-design-and-variables" class="nav-link active" data-scroll-target="#identifying-the-survey-design-and-variables">Identifying the survey design and variables</a></li>
  <li><a href="#specifying-the-survey-design-in-stata" id="toc-specifying-the-survey-design-in-stata" class="nav-link" data-scroll-target="#specifying-the-survey-design-in-stata">Specifying the survey design in Stata</a></li>
  <li><a href="#mean-age-and-its-95-confidence-interval" id="toc-mean-age-and-its-95-confidence-interval" class="nav-link" data-scroll-target="#mean-age-and-its-95-confidence-interval">Mean age and its 95% confidence interval</a></li>
  <li><a href="#proportions-and-their-95-confidence-interval" id="toc-proportions-and-their-95-confidence-interval" class="nav-link" data-scroll-target="#proportions-and-their-95-confidence-interval">Proportions and their 95% confidence interval</a></li>
  <li><a href="#domain-estimates" id="toc-domain-estimates" class="nav-link" data-scroll-target="#domain-estimates">Domain estimates</a></li>
  <li><a href="#inference-without-survey-design-variables" id="toc-inference-without-survey-design-variables" class="nav-link" data-scroll-target="#inference-without-survey-design-variables">Inference without survey design variables</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_R.html">5. Exercises</a></li><li class="breadcrumb-item"><a href="./07_Stata.html">Stata</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Stata</h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<p>Stata provides comprehensive support for computing estimates from survey data using weights and survey design variables. Perhaps a bit confusingly to some users, it distinguishes between four weighted estimation techniques, also called <em>weights</em>:</p>
<ul>
<li>frequency weights (<code>fweight</code>)<br>
</li>
<li>analytical weights (<code>aweight</code>),</li>
<li>importance weights (<code>iweight</code>) and</li>
<li>probability weights (<code>pweight</code>).</li>
</ul>
<p>These mostly differ in the way standard errors are estimated.</p>
<p>In most cases, survey weights available in UKDS datasets should be treated as <em>probability weights</em> in Stata jargon. Indeed not all of the above weighting methods were designed to work with survey data.</p>
<p>As other statistical software, weighted estimation in Stata can either be performed:</p>
<ul>
<li>as a two stage process consisting of first declaring the current dataset in memory to be survey data (using <code>svyset</code>), then run survey data-specific estimation commands using the <code>svy:</code> prefix.</li>
<li>or by specifying weights alongside standard estimation commands ie <code>command based</code> or <code>casual</code>weighting.</li>
</ul>
<p>At the same time, a feature of Stata is that a number of basic estimation commands, such as <code>summarise</code> or <code>tabulate</code>. This is meant to nudge users of survey data to prioritise the survey estimation commands rather than command-based weighting.</p>
<p>In the example below, we will practice statistical inference with data from the <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=8450">2017 British Social Attitudes Survey (BSA)</a> taking into account weights and survey design variables. Please note that at the time of writing this document only some issues of the BSA include survey design variables.</p>
<section id="identifying-the-survey-design-and-variables" class="level2">
<h2 class="anchored" data-anchor-id="identifying-the-survey-design-and-variables">Identifying the survey design and variables</h2>
<p>We first need to find out about the survey design that was used in the 2017 BSA, and the design variables that are made available in the dataset. Such information can usually be found in the documentation that comes together with the data under the <code>mrdoc/pdf</code> folder.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 1</strong> <em>What was the design used in this survey (i.e.&nbsp;think stages and units sampled). What were the primary sampling units; the strata (if relevant)?</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>The 2017 BSA is a three stage stratified random survey, with postcode sectors, adresses and individuals as the units selected at each stage. Primary sampling units were stratified according to geographies (sub regions), population density, and proportion of owner-occupiers. Sampling rate was proportional to the size of postcode sectors (i.e.&nbsp;number of addresses).</em></p>
</div>
</div>
</div>
<hr>
<p>Now that we are a bit more familiar with the way the survey was designed, we need to try and identify the design variables we can include when producing estimates. The information can usually be found in the user manual or the data dictionary available under <code>mrdoc/ukda_data_dictionaries.zip</code> The file may need to be decompressed separately.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 2</strong> <em>What survey design variables are available? Are there any ones that are missing – if so which ones? What is the name of the weights variables?</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>From the Data Dictionary it appears that the primary sampling units (sub regions) are identified by <code>Spoint</code> and the strata by <code>StratID</code>. The weights variable is <code>WtFactor</code>. Addresses are not provided but could be approximated with a household identifier.</em></p>
</div>
</div>
</div>
<hr>
</section>
<section id="specifying-the-survey-design-in-stata" class="level2">
<h2 class="anchored" data-anchor-id="specifying-the-survey-design-in-stata">Specifying the survey design in Stata</h2>
<p>We first need to open the BSA dataset.</p>
<div id="5b721aa8" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1"></a>*** Setting the working directory</span>
<span id="cb1-2"><a href="#cb1-2"></a>*** Edit the <span class="kw">line</span> below  <span class="kw">as</span> appropriate</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">quietly</span>  cd ~/OneDrive/SSP/DSP-core-inference </span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="kw">use</span> ~/Data/bsa/UKDA-8450-stata/bsa2017_for_ukda.dta</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a>*** We <span class="kw">use</span> the <span class="kw">short</span> option <span class="kw">in</span> <span class="kw">order</span> to avoid </span>
<span id="cb1-8"><a href="#cb1-8"></a>*** <span class="ot">all</span> variables <span class="kw">in</span> the dataset to <span class="kw">be</span> <span class="ot">list</span></span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="kw">describe</span>, <span class="kw">short</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<style>div.jp-Notebook .datagrid-container {min-height: 448px; }</style>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Setting the working directory
. *** Edit the line below  as appropriate
. quietly  cd ~/OneDrive/SSP/DSP-core-inference 

. 
. use ~/Data/bsa/UKDA-8450-stata/bsa2017_for_ukda.dta

. 
. *** We use the short option in order to avoid 
. *** all variables in the dataset to be list
. 
. describe, short 

Contains data from ~/Data/bsa/UKDA-8450-stata/bsa2017_for_ukda.dta
 Observations:         3,988                  
    Variables:           580                  09 FEB 2021 09:29
Sorted by: 

. </code></pre>
</div>
</div>
<p>We can now specify the survey design earlier identified in the data documentation using:</p>
<ul>
<li><code>Spoint</code> as Primary Sampling Unit;</li>
<li><code>StratID</code> as strata…</li>
<li>and <code>WtFactor</code> as weights.</li>
</ul>
<p>The Stata command to do this is <code>svyset</code>.</p>
<div id="82d44609" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1"></a>*** First examine the survey design variables</span>
<span id="cb3-2"><a href="#cb3-2"></a></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="kw">describe</span> Spoint StratID WtFactor</span>
<span id="cb3-4"><a href="#cb3-4"></a></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="kw">svyset</span> Spoint [pw=WtFactor], <span class="kw">strata</span>(StratID)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** First examine the survey design variables
. 
. describe Spoint StratID WtFactor

Variable      Storage   Display    Value
    name         type    format    label      Variable label
-------------------------------------------------------------------------------
Spoint          int     %8.0g                 Sample point
StratID         int     %8.0g                 Stratification ID
WtFactor        double  %12.0g                Final BSA weight

. 
. svyset Spoint [pw=WtFactor], strata(StratID)

Sampling weights: WtFactor
             VCE: linearized
     Single unit: missing
        Strata 1: StratID
 Sampling unit 1: Spoint
           FPC 1: &lt;zero&gt;

. </code></pre>
</div>
</div>
</section>
<section id="mean-age-and-its-95-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="mean-age-and-its-95-confidence-interval">Mean age and its 95% confidence interval</h2>
<p>We can now produce a first set of estimates and compare it with those we would have got without accounting for the survey design. We will compute the average (i.e.&nbsp;mean) age of respondents. From this point, we will are going to use the <code>svy:</code> prefix before Stata estimation commands, so that our estimates are informed by the survey design.</p>
<div id="af9f5fa5" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1"></a><span class="kw">svy</span>:<span class="kw">mean</span> RAgeE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. svy:mean RAgeE
(running mean on estimation sample)

Survey: Mean estimation

Number of strata = 159            Number of obs   =      3,988
Number of PSUs   = 372            Population size = 3,988.0019
                                  Design df       =        213

--------------------------------------------------------------
             |             Linearized
             |       Mean   std. err.     [95% conf. interval]
-------------+------------------------------------------------
       RAgeE |   48.31309   .4235811      47.47815    49.14804
--------------------------------------------------------------</code></pre>
</div>
</div>
<p>By default <code>svy:mean</code> computes both the standard error of the mean and its confidence interval.</p>
<p>From the above results, we can see that back in 2017 the mean age of the British population aged 16 and over was likely to range between 47.5 and 49.1 years.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 3</strong> <em>What would be the consequences of weighing but not accounting for the sample design; not using weights and accounting for the sample design on estimating the mean and its confidence interval</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Not using weights would make us overestimate the mean age in the population (of those aged 16+) by about 4 years. This is likely to be due to the fact that older respondents are more likely to take part to surveys.</li>
</ul>
<div id="ad4f1020" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">mean</span> RAgeE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. mean RAgeE

Mean estimation                          Number of obs = 3,988

--------------------------------------------------------------
             |       Mean   Std. err.     [95% conf. interval]
-------------+------------------------------------------------
       RAgeE |   52.19358   .2872482      51.63041    52.75675
--------------------------------------------------------------</code></pre>
</div>
</div>
<ul>
<li>Not using survey design variables does not alter the value of the estimated population mean. However, this would lead us to - marginally - overestimate the precision/underestimate the uncertainty of our estimate with a narrower confidence interval ie between 47.6 and 49 years, that is by a little bit more than a month in each direction.</li>
</ul>
<div id="c253fb62" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1"></a>*** Declaring survey design <span class="kw">as</span> simple random</span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="kw">svyset</span> [pw=WtFactor]</span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="kw">svy</span>:<span class="kw">mean</span> RAgeE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Declaring survey design as simple random
. svyset [pw=WtFactor]

Sampling weights: WtFactor
             VCE: linearized
     Single unit: missing
        Strata 1: &lt;one&gt;
 Sampling unit 1: &lt;observations&gt;
           FPC 1: &lt;zero&gt;

. svy:mean RAgeE
(running mean on estimation sample)

Survey: Mean estimation

Number of strata =     1          Number of obs   =      3,988
Number of PSUs   = 3,988          Population size = 3,988.0019
                                  Design df       =      3,987

--------------------------------------------------------------
             |             Linearized
             |       Mean   std. err.     [95% conf. interval]
-------------+------------------------------------------------
       RAgeE |   48.31309   .3435013      47.63964    48.98655
--------------------------------------------------------------

. </code></pre>
</div>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="proportions-and-their-95-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="proportions-and-their-95-confidence-interval">Proportions and their 95% confidence interval</h2>
<p>We can similarly estimate the distribution of a categorical variable in the population by computing proportions (or percentages), for instance, the proportion of people who declare that they are interested in politics. This is the <code>Politics</code> variable in the BSA. It has five categories ranging from 1 - ‘A great deal’ to 5 - ‘None at all’. We are going to recode it into a dichotomic variable with 1 and 2 - <code>quite a lot</code> and as ‘Significantly’, and the rest as ‘Not so much’.</p>
<div id="463acc97" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1"></a>*** Overview <span class="kw">of</span> the <span class="kw">variable</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>inspect Politics</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a>*** Frequency distribution</span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="kw">tab</span> Politics</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Overview of the variable
. inspect Politics

Politics:  How much interest do you have        Number of observations
-------------------------------------------------------------------------------
                                             Total      Integers   Nonintegers
|  #                         Negative            -             -             -
|  #                         Zero                -             -             -
|  #   #                     Positive        3,988         3,988             -
|  #   #   #                           -----------   -----------   -----------
|  #   #   #                 Total           3,988         3,988             -
|  #   #   #   .   .         Missing             -
+----------------------                -----------
1                     8                      3,988
   (6 unique values)

      Politics is labeled and all values are documented in the label.

. 
. *** Frequency distribution
. tab Politics

   How much interest do |
  you have in politics? |      Freq.     Percent        Cum.
------------------------+-----------------------------------
      ... a great deal, |        739       18.53       18.53
           quite a lot, |        982       24.62       43.15
                  some, |      1,179       29.56       72.72
         not very much, |        708       17.75       90.47
       or, none at all? |        379        9.50       99.97
             Don`t know |          1        0.03      100.00
------------------------+-----------------------------------
                  Total |      3,988      100.00

. </code></pre>
</div>
</div>
<p>Let’s create the dichotomic version and look at the results:</p>
<div id="b550bece" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1"></a><span class="kw">recode</span> Politics 1 2=1 3/<span class="fu">max</span>=0, <span class="kw">gen</span>(DPol)</span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a>*** Labelling the <span class="kw">variable</span></span>
<span id="cb13-4"><a href="#cb13-4"></a>lab def LDPol 0 <span class="st">"Not so much"</span> 1 <span class="st">"Significantly"</span></span>
<span id="cb13-5"><a href="#cb13-5"></a>lab val DPol LDPol</span>
<span id="cb13-6"><a href="#cb13-6"></a></span>
<span id="cb13-7"><a href="#cb13-7"></a>*** Frequency distribution</span>
<span id="cb13-8"><a href="#cb13-8"></a><span class="kw">tab</span> Politics DPol </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. recode Politics 1 2=1 3/max=0, gen(DPol)
(3,249 differences between Politics and DPol)

. 
. *** Labelling the variable
. lab def LDPol 0 "Not so much" 1 "Significantly"

. lab val DPol LDPol

. 
. *** Frequency distribution
. tab Politics DPol 

                      |  RECODE of Politics
                      | (How much interest do
                      |      you have in
 How much interest do |      politics?)
you have in politics? | Not so mu  Significa |     Total
----------------------+----------------------+----------
    ... a great deal, |         0        739 |       739 
         quite a lot, |         0        982 |       982 
                some, |     1,179          0 |     1,179 
       not very much, |       708          0 |       708 
     or, none at all? |       379          0 |       379 
           Don`t know |         1          0 |         1 
----------------------+----------------------+----------
                Total |     2,267      1,721 |     3,988 

. </code></pre>
</div>
</div>
<p>We can now estimate the proportion of people significantly interested in politics in the population. We just need to add <code>ci</code> as an option in order to also get the 95% confidence interval.</p>
<div id="8eed679e" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1"></a>*** Let's <span class="kw">not</span> forget to declare the survey design again</span>
<span id="cb15-2"><a href="#cb15-2"></a></span>
<span id="cb15-3"><a href="#cb15-3"></a>*** We need to declare again the survey design after the <span class="fu">last</span> exercise</span>
<span id="cb15-4"><a href="#cb15-4"></a><span class="kw">svyset</span> Spoint [pw=WtFactor], <span class="kw">strata</span>(StratID)</span>
<span id="cb15-5"><a href="#cb15-5"></a></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="kw">svy</span>:<span class="kw">tab</span> DPol,<span class="kw">percent</span> <span class="kw">ci</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Let's not forget to declare the survey design again
. 
. *** We need to declare again the survey design after the last exercise
. svyset Spoint [pw=WtFactor], strata(StratID)

Sampling weights: WtFactor
             VCE: linearized
     Single unit: missing
        Strata 1: StratID
 Sampling unit 1: Spoint
           FPC 1: &lt;zero&gt;

. 
. svy:tab DPol,percent ci
(running tabulate on estimation sample)

Number of strata = 159                            Number of obs   =      3,988
Number of PSUs   = 372                            Population size = 3,988.0019
                                                  Design df       =        213

----------------------------------------------
RECODE of |
Politics  |
(How much |
interest  |
do you    |
have in   |
politics? |
)         | percentage          lb          ub
----------+-----------------------------------
 Not so m |      56.99       55.06        58.9
 Signific |      43.01        41.1       44.94
          | 
    Total |        100                        
----------------------------------------------
Key: percentage = Cell percentage
             lb = Lower 95% confidence bound for cell percentage
             ub = Upper 95% confidence bound for cell percentage

. </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 4</strong> <em>What is the proportion of respondents aged 17-34 in the sample, as well as its 95% confidence interval? You can use <code>RAgecat5</code></em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>The proportion of 17-34 year old in the sample is</li>
</ul>
<div id="865a9dc1" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb17-1"><a href="#cb17-1"></a><span class="kw">svy</span>:<span class="kw">tab</span> RAgecat5, <span class="kw">percent</span> <span class="kw">ci</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. svy:tab RAgecat5, percent ci
(running tabulate on estimation sample)

Number of strata = 159                            Number of obs   =      3,988
Number of PSUs   = 372                            Population size = 3,988.0019
                                                  Design df       =        213

----------------------------------------------
Age of    |
responden |
t(grouped |
)         |
&lt;3-catego |
ry&gt; dv    | percentage          lb          ub
----------+-----------------------------------
    17-34 |      28.46       26.46       30.56
    35-54 |      33.98        32.3       35.69
      55+ |       37.5       35.67       39.36
   DK/Ref |      .0601       .0214       .1683
          | 
    Total |        100                        
----------------------------------------------
Key: percentage = Cell percentage
             lb = Lower 95% confidence bound for cell percentage
             ub = Upper 95% confidence bound for cell percentage</code></pre>
</div>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="domain-estimates" class="level2">
<h2 class="anchored" data-anchor-id="domain-estimates">Domain estimates</h2>
<p><em>Domain estimates</em> refer to estimates for groups or subpopulations, which adds a layer of complexity to what we have done so far. They key point is that as survey weights are usually designed by data producers using the whole of the sample, confidence intervals and standard errors computed using only part of the sample - such as for example when subsetting the dataset or removing observations - may be unreliable, as they will rely on some of the weights only. Instead, it is recommended to use commands that take into account the entire distribution of the weights.</p>
<p>In Stata, this can be either achieved with <code>subpop()</code> or <code>over</code>.</p>
<p><code>subpop()</code> computes estimates for single groups identified either by a dummy variable (ie coded 0-1), or by a conditional statement. For instance, if we would like to know the mean age of BSA respondents in the North East, we need to specify (using the Government Office Regions <code>GOR_ID</code> variable):</p>
<div id="0233f2a4" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb19-1"><a href="#cb19-1"></a><span class="kw">svy</span>, subpop(<span class="kw">if</span> GOR_ID==1):<span class="kw">mean</span> RAgeE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. svy, subpop(if GOR_ID==1):mean RAgeE
(running mean on estimation sample)

Survey: Mean estimation

Number of strata =  8             Number of obs   =        214
Number of PSUs   = 19             Population size = 199.035253
                                  Subpop. no. obs =        180
                                  Subpop. size    = 167.274844
                                  Design df       =         11

--------------------------------------------------------------
             |             Linearized
             |       Mean   std. err.     [95% conf. interval]
-------------+------------------------------------------------
       RAgeE |   46.10143   1.269496      43.30729    48.89557
--------------------------------------------------------------
Note: 151 strata omitted because they contain no subpopulation
      members.</code></pre>
</div>
</div>
<p>The above would be identical to:</p>
<div id="9dc0e660" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb21-1"><a href="#cb21-1"></a>*** Creates dummy variables with the category number <span class="kw">as</span> suffix</span>
<span id="cb21-2"><a href="#cb21-2"></a><span class="kw">quietly</span> <span class="kw">tab</span> GOR_ID ,<span class="kw">gen</span>(region) </span>
<span id="cb21-3"><a href="#cb21-3"></a></span>
<span id="cb21-4"><a href="#cb21-4"></a><span class="kw">svy</span>, subpop(region1): <span class="kw">mean</span> RAgeE, cformat(%9.1f)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Creates dummy variables with the category number as suffix
. quietly tab GOR_ID ,gen(region) 

. 
. svy, subpop(region1): mean RAgeE, cformat(%9.1f)
(running mean on estimation sample)

Survey: Mean estimation

Number of strata =  8             Number of obs   =        214
Number of PSUs   = 19             Population size = 199.035253
                                  Subpop. no. obs =        180
                                  Subpop. size    = 167.274844
                                  Design df       =         11

--------------------------------------------------------------
             |             Linearized
             |       Mean   std. err.     [95% conf. interval]
-------------+------------------------------------------------
       RAgeE |       46.1        1.3          43.3        48.9
--------------------------------------------------------------
Note: 151 strata omitted because they contain no subpopulation
      members.

. </code></pre>
</div>
</div>
<p>In case there are more than a few subpopulations, Stata provides the ‘over’ option, that can be used with in conjunction with estimation commands. In our case:</p>
<div id="fee033a0" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb23-1"><a href="#cb23-1"></a><span class="kw">svy</span>: <span class="kw">mean</span> RAgeE,<span class="bn">over</span>(GOR_ID) cformat(%9.1f)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. svy: mean RAgeE,over(GOR_ID) cformat(%9.1f)
(running mean on estimation sample)

Survey: Mean estimation

Number of strata = 159                           Number of obs   =      3,988
Number of PSUs   = 372                           Population size = 3,988.0019
                                                 Design df       =        213

-----------------------------------------------------------------------------
                            |             Linearized
                            |       Mean   std. err.     [95% conf. interval]
----------------------------+------------------------------------------------
             c.RAgeE@GOR_ID |
              A North East  |       46.1        1.3          43.6        48.6
              B North West  |       49.6        1.2          47.2        52.0
D Yorkshire and The Humber  |       48.0        1.4          45.2        50.8
           E East Midlands  |       48.6        1.4          45.9        51.4
           F West Midlands  |       48.1        1.6          45.0        51.2
         G East of England  |       49.0        1.5          46.0        52.1
                  H London  |       45.0        1.0          43.0        46.9
              J South East  |       48.0        1.4          45.1        50.8
              K South West  |       53.4        0.9          51.5        55.2
                   L Wales  |       49.1        2.0          45.1        53.1
                M Scotland  |       47.3        1.4          44.7        50.0
-----------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Our results seem to suggest that the population in London is among the youngest in the country, and that those in the South West are among the oldest – their respective 95% confidence intervals do not overlap. We should not feel so confident about differences between London and the South East, as the CIs partially overlap.</p>
<p>We can follow a similar approach with proportions: we just need to specify the variable we are interested in as an outcome, for instance respondents who are significantly interested in politics, and either replace <code>mean</code> with <code>proportion</code> or even more simply use <code>tab</code>:</p>
<div id="85b4a31d" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb25-1"><a href="#cb25-1"></a><span class="kw">svy</span>:<span class="kw">proportion</span> DPol, <span class="kw">percent</span> <span class="bn">over</span>(GOR_ID) </span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="kw">svy</span>:<span class="kw">tab</span> GOR_ID DPol, <span class="ot">row</span> <span class="kw">percent</span>  <span class="kw">ci</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. svy:proportion DPol, percent over(GOR_ID) 
(running proportion on estimation sample)

Survey: Percent estimation

Number of strata = 159                            Number of obs   =      3,988
Number of PSUs   = 372                            Population size = 3,988.0019
                                                  Design df       =        213

------------------------------------------------------------------------------
                             |             Linearized            Logit
                             |    Percent   std. err.     [95% conf. interval]
-----------------------------+------------------------------------------------
                 DPol@GOR_ID |
   Not so much A North East  |      66.62       3.12         60.21       72.46
   Not so much B North West  |      58.09       2.91         52.26       63.70
                Not so much #|
 D Yorkshire and The Humber  |      64.42       3.23         57.84       70.51
Not so much E East Midlands  |      63.09       1.92         59.23       66.79
Not so much F West Midlands  |      63.67       2.41         58.79       68.28
                Not so much #|
          G East of England  |      52.82       2.78         47.33       58.24
       Not so much H London  |      45.77       3.37         39.25       52.45
   Not so much J South East  |      55.35       2.97         49.46       61.10
   Not so much K South West  |      53.46       3.47         46.60       60.18
        Not so much L Wales  |      61.42       5.16         50.90       70.97
     Not so much M Scotland  |      57.26       3.30         50.67       63.60
 Significantly A North East  |      33.38       3.12         27.54       39.79
 Significantly B North West  |      41.91       2.91         36.30       47.74
              Significantly #|
 D Yorkshire and The Humber  |      35.58       3.23         29.49       42.16
              Significantly #|
            E East Midlands  |      36.91       1.92         33.21       40.77
              Significantly #|
            F West Midlands  |      36.33       2.41         31.72       41.21
              Significantly #|
          G East of England  |      47.18       2.78         41.76       52.67
     Significantly H London  |      54.23       3.37         47.55       60.75
 Significantly J South East  |      44.65       2.97         38.90       50.54
 Significantly K South West  |      46.54       3.47         39.82       53.40
      Significantly L Wales  |      38.58       5.16         29.03       49.10
   Significantly M Scotland  |      42.74       3.30         36.40       49.33
------------------------------------------------------------------------------

. svy:tab GOR_ID DPol, row percent  ci 
(running tabulate on estimation sample)

Number of strata = 159                            Number of obs   =      3,988
Number of PSUs   = 372                            Population size = 3,988.0019
                                                  Design df       =        213

-------------------------------------------------------
2007      |
version : |
Governmen |RECODE of Politics (How much interest do you
t office  |             have in politics?)             
region    |      Not so m       Signific          Total
----------+--------------------------------------------
  A North |         66.62          33.38            100
          | [60.21,72.46]  [27.54,39.79]               
          | 
  B North |         58.09          41.91            100
          |  [52.26,63.7]   [36.3,47.74]               
          | 
 D Yorksh |         64.42          35.58            100
          | [57.84,70.51]  [29.49,42.16]               
          | 
 E East M |         63.09          36.91            100
          | [59.23,66.79]  [33.21,40.77]               
          | 
 F West M |         63.67          36.33            100
          | [58.79,68.28]  [31.72,41.21]               
          | 
 G East o |         52.82          47.18            100
          | [47.33,58.24]  [41.76,52.67]               
          | 
 H London |         45.77          54.23            100
          | [39.25,52.45]  [47.55,60.75]               
          | 
  J South |         55.35          44.65            100
          |  [49.46,61.1]   [38.9,50.54]               
          | 
  K South |         53.46          46.54            100
          |  [46.6,60.18]   [39.82,53.4]               
          | 
  L Wales |         61.42          38.58            100
          |  [50.9,70.97]   [29.03,49.1]               
          | 
 M Scotla |         57.26          42.74            100
          |  [50.67,63.6]   [36.4,49.33]               
          | 
    Total |         56.99          43.01            100
          |  [55.06,58.9]   [41.1,44.94]               
-------------------------------------------------------
Key: Row percentage
     [95% confidence interval for row percentage]

  Pearson:
    Uncorrected   chi2(10)        =   59.5640
    Design-based  F(8.74, 1860.92)=    4.0419     P = 0.0000

. </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 5</strong> <em>What is the 95% confidence interval for the proportion of people interested in politics in the South West? Is the proportion likely to be different in London? In what way? What is the region of the UK for which the precision of the estimates is likely to be the smallest?</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 95% confidence interval for the proportion of people interested in politics in the South West in 2017 was 39.8-53.4. By contrast, it was 47.6-60.8 in London. The region with the lowest precision of estimates (i.e.&nbsp;the widest confidence interval) was Wales, with a 20 percentage point difference between the upper and lower bounds of the confidence interval.</p>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Question 6</strong> *Using interest in politics as before, and three category age <code>RAgecat5</code>: 1. Produce a table of results showing the proportion of respondents significantly interested in politics by age group and gender; 2. Assess whether the age difference in interest in politics is similar for each gender; 3. Based on the data, is it fair to say that men aged under 35 tend to be more likely to declare themselves interested in politics than women aged 55 and above?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="7bd562b4" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb27-1"><a href="#cb27-1"></a><span class="kw">svy</span>,subpop(<span class="kw">if</span> RAgecat5==1 &amp; Rsex==1): <span class="kw">proportion</span> DPol,<span class="kw">percent</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="kw">svy</span>: <span class="kw">proportion</span> DPol,<span class="bn">over</span>(RAgecat5 Rsex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. svy,subpop(if RAgecat5==1 &amp; Rsex==1): proportion DPol,percent
(running proportion on estimation sample)

Survey: Percent estimation

Number of strata = 138              Number of obs   =      3,591
Number of PSUs   = 326              Population size = 3,608.3226
                                    Subpop. no. obs =        339
                                    Subpop. size    = 573.962978
                                    Design df       =        188

----------------------------------------------------------------
               |             Linearized            Logit
               |    Percent   std. err.     [95% conf. interval]
---------------+------------------------------------------------
          DPol |
  Not so much  |      57.28       2.64         52.02       62.38
Significantly  |      42.72       2.64         37.62       47.98
----------------------------------------------------------------
Note: 21 strata omitted because they contain no subpopulation
      members.

. svy: proportion DPol,over(RAgecat5 Rsex)
(running proportion on estimation sample)

Survey: Proportion estimation

Number of strata = 159                            Number of obs   =      3,988
Number of PSUs   = 372                            Population size = 3,988.0019
                                                  Design df       =        213

------------------------------------------------------------------------------
                             |             Linearized            Logit
                             | Proportion   std. err.     [95% conf. interval]
-----------------------------+------------------------------------------------
          DPol@RAgecat5#Rsex |
     Not so much 17-34#Male  |   .5728105   .0263534      .5202484    .6237784
   Not so much 17-34#Female  |   .7368923   .0228962      .6893531    .7794836
     Not so much 35-54#Male  |   .4921008   .0210396      .4507772    .5335326
   Not so much 35-54#Female  |   .6587693   .0180841      .6222803    .6934697
       Not so much 55+#Male  |   .4220344   .0197446      .3836731    .4613601
     Not so much 55+#Female  |    .569871   .0175356      .5350198    .6040433
    Not so much DK/Ref#Male  |          1          .             .           .
  Not so much DK/Ref#Female  |          0  (no observations)
   Significantly 17-34#Male  |   .4271895   .0263534      .3762216    .4797516
 Significantly 17-34#Female  |   .2631077   .0228962      .2205164    .3106469
   Significantly 35-54#Male  |   .5078992   .0210396      .4664674    .5492228
 Significantly 35-54#Female  |   .3412307   .0180841      .3065303    .3777197
     Significantly 55+#Male  |   .5779656   .0197446      .5386399    .6163269
   Significantly 55+#Female  |    .430129   .0175356      .3959567    .4649802
  Significantly DK/Ref#Male  |          0  (no observations)
Significantly DK/Ref#Female  |          1          .             .           .
------------------------------------------------------------------------------

. </code></pre>
</div>
</div>
<p>Older respondents both male and female tend to be more involved in politics than younger ones.</p>
<p>The confidence interval for the proportion of men under 35 and women above 55 interested in politics overlaps; it is unlikely that they differ in the population.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="inference-without-survey-design-variables" class="level2">
<h2 class="anchored" data-anchor-id="inference-without-survey-design-variables">Inference without survey design variables</h2>
<p><em>Example: count and proportion of the regional population of the UK using Quarterly Labour Force Survey safeguarded data</em></p>
<p>As a rule, safeguarded versions of the LFS do not include sample design variables. On the other hand they include two weight variables:</p>
<ul>
<li><code>pwt22</code> for estimation with the whole sample</li>
<li><code>piwt22</code> for estimation of income using respondents currently in employment (and accounting for the high level of non response for the earnings variables)</li>
</ul>
<p>Estimation without accounting for sample design will likely be biased and should be reported as such including warnings, even if the nature (over or underestimation of the precision) and and size are not known. An alternative is to look for design effects tables published by the data producer which could be used to correct for the bias.</p>
<p>The Office for National Statistics regularly publishes such tables for the LFS, albeit mostly for their headline statistics. Obtaining further design effects for subpopulations might not be straighforward. The overall methodology is described <a href="https://www.ons.gov.uk/methodology/methodologicalpublications/generalmethodology/onsworkingpaperseries/onsmethodologyworkingpaperseriesno9guidetocalculatingstandarderrorsforonssocialsurveys#annex-a-labour-force-survey-standard-errors-january-to-march-2015-united-kingdom">in this note</a>, and updated tables are provided <a href="Volume 1: Background and methodology (PDF, 1.2MB)">on this page</a>.</p>
<p>Let’s see how this can be achieved. But first, let’s produce uncorrected ‘naive’ estimates of the regional population.</p>
<div id="a8891af0" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb29-1"><a href="#cb29-1"></a><span class="kw">clear</span> </span>
<span id="cb29-2"><a href="#cb29-2"></a><span class="kw">use</span> ~/Data/lfs/UKDA-8999-stata/lfsp_aj22_eul_pwt22.dta</span>
<span id="cb29-3"><a href="#cb29-3"></a></span>
<span id="cb29-4"><a href="#cb29-4"></a><span class="kw">svyset</span> [pw=PIWT22] </span>
<span id="cb29-5"><a href="#cb29-5"></a></span>
<span id="cb29-6"><a href="#cb29-6"></a>*** Counts the number <span class="kw">of</span> valid cases <span class="kw">for</span> the SEX <span class="kw">variable</span></span>
<span id="cb29-7"><a href="#cb29-7"></a><span class="kw">svy</span>:<span class="kw">total</span> SEX, <span class="bn">over</span>(URESMC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. clear 

. use ~/Data/lfs/UKDA-8999-stata/lfsp_aj22_eul_pwt22.dta

. 
. svyset [pw=PIWT22] 

Sampling weights: PIWT22
             VCE: linearized
     Single unit: missing
        Strata 1: &lt;one&gt;
 Sampling unit 1: &lt;observations&gt;
           FPC 1: &lt;zero&gt;

. 
. *** Counts the number of valid cases for the SEX variable
. svy:total SEX, over(URESMC)
(running total on estimation sample)

Survey: Total estimation

Number of strata =      1                        Number of obs   =     75,992
Number of PSUs   = 75,992                        Population size = 28,327,129
                                                 Design df       =     75,991

-----------------------------------------------------------------------------
                            |             Linearized
                            |      Total   std. err.     [95% conf. interval]
----------------------------+------------------------------------------------
               c.SEX@URESMC |
               Tyne &amp; Wear  |     711226   70420.39      573202.4    849249.6
   Rest of Northern region  |    1138483   74814.36      991847.2     1285119
           South Yorkshire  |     674216   65640.17      545561.6    802870.4
            West Yorkshire  |    1514892   97543.74       1323707     1706077
Rest of Yorks &amp; Humberside  |    1203435   84752.98       1037320     1369550
             East Midlands  |    3084354   139855.5       2810238     3358470
               East Anglia  |    1737856   108910.1       1524393     1951319
              Inner London  |    2486698   217962.9       2059492     2913904
              Outer London  |    3425496   199794.6       3033900     3817092
        Rest of South East  |    8146349   266897.6       7623231     8669467
                South West  |    3529068   153618.8       3227976     3830160
West Midlands (met county)  |    1628710   136654.7       1360868     1896552
     Rest of West Midlands  |    2096013   127469.1       1846174     2345852
        Greater Manchester  |    1759917   118336.3       1527978     1991856
                Merseyside  |     942263     112404      721951.8     1162574
        Rest of North West  |    1585060   108062.8       1373257     1796863
                     Wales  |    1865801   121156.4       1628335     2103267
               Strathclyde  |    1329341   114407.4       1105103     1553579
          Rest of Scotland  |    2344507   155628.7       2039476     2649538
          Northern Ireland  |    1119091   44878.71       1031129     1207053
-----------------------------------------------------------------------------

. </code></pre>
</div>
</div>
<p>In the above example, we are working with the most commonly used flavour of the Labour Force Survey: the quarterly edition. The specific dataset used above is the April-July 2022 issue. Looking at the latest version of the documentation mentioned above - Volume 1, Annex C, we can see a list of design effects for the number of employed respondents by Region of Usual Residence.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pics/lfs_vol1_SE.png" class="img-fluid figure-img" alt="Screenshot of LFS documentation Volume 1, Annex C showing Design Effects"></p>
<figcaption>LFS design factors</figcaption>
</figure>
</div>
<p>We can see that for some reason, the number of regions has been reduced from the original 16 to 13. We therefore need to recode our original variable.</p>
<div id="759156ed" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb31-1"><a href="#cb31-1"></a>*** Recoding</span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="kw">recode</span> URESMC 1 2=1 3 4 5 =2 8 9=8 12 13 =12 14 16 =14 18 19=18,<span class="kw">gen</span>(rURESMC)</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a>*** Adapting <span class="kw">values</span> labels</span>
<span id="cb31-5"><a href="#cb31-5"></a>lab copy URESMC ur2</span>
<span id="cb31-6"><a href="#cb31-6"></a>lab def ur2 1 <span class="st">"North East"</span> 2 <span class="st">"Yorkshire &amp; Humber"</span> 8 <span class="st">"London"</span> 12 <span class="st">"West Midlands"</span> 14 <span class="st">"North West"</span> 18 <span class="st">"Scotland"</span>,modify</span>
<span id="cb31-7"><a href="#cb31-7"></a>lab val  rURESMC ur2</span>
<span id="cb31-8"><a href="#cb31-8"></a></span>
<span id="cb31-9"><a href="#cb31-9"></a>*** Checking the results</span>
<span id="cb31-10"><a href="#cb31-10"></a><span class="kw">tab</span> rURESMC</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. *** Recoding
. recode URESMC 1 2=1 3 4 5 =2 8 9=8 12 13 =12 14 16 =14 18 19=18,gen(rURESMC)
(23,406 differences between URESMC and rURESMC)

. 
. *** Adapting values labels
. lab copy URESMC ur2

. lab def ur2 1 "North East" 2 "Yorkshire &amp; Humber" 8 "London" 12 "West Midland
&gt; s" 14 "North West" 18 "Scotland",modify

. lab val  rURESMC ur2

. 
. *** Checking the results
. tab rURESMC

  RECODE of URESMC (Region |
       of usual residence) |      Freq.     Percent        Cum.
---------------------------+-----------------------------------
                North East |      4,249        5.59        5.59
        Yorkshire &amp; Humber |      6,435        8.47       14.06
             East Midlands |      5,701        7.50       21.56
               East Anglia |      3,114        4.10       25.66
                    London |      6,523        8.58       34.24
        Rest of South East |     13,725       18.06       52.30
                South West |      7,237        9.52       61.83
             West Midlands |      6,089        8.01       69.84
                North West |      5,501        7.24       77.08
                Merseyside |        993        1.31       78.39
                     Wales |      3,750        4.93       83.32
                  Scotland |      5,626        7.40       90.72
          Northern Ireland |      7,049        9.28      100.00
---------------------------+-----------------------------------
                     Total |     75,992      100.00

. </code></pre>
</div>
</div>
<p>Let us now produce the updated population estimates:</p>
<div id="8c9cd922" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb33-1"><a href="#cb33-1"></a><span class="kw">svy</span>:<span class="kw">total</span> SEX, <span class="bn">over</span>(rURESMC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. svy:total SEX, over(rURESMC)
(running total on estimation sample)

Survey: Total estimation

Number of strata =      1                Number of obs   =     75,992
Number of PSUs   = 75,992                Population size = 28,327,129
                                         Design df       =     75,991

---------------------------------------------------------------------
                    |             Linearized
                    |      Total   std. err.     [95% conf. interval]
--------------------+------------------------------------------------
      c.SEX@rURESMC |
        North East  |    1849709   102546.1       1648719     2050699
Yorkshire &amp; Humber  |    3392543   144303.8       3109708     3675378
     East Midlands  |    3084354   139855.5       2810238     3358470
       East Anglia  |    1737856   108910.1       1524393     1951319
            London  |    5912194   294956.8       5334080     6490308
Rest of South East  |    8146349   266897.6       7623231     8669467
        South West  |    3529068   153618.8       3227976     3830160
     West Midlands  |    3724723   186419.1       3359342     4090104
        North West  |    3344977   159817.1       3031736     3658218
        Merseyside  |     942263     112404      721951.8     1162574
             Wales  |    1865801   121156.4       1628335     2103267
          Scotland  |    3673848   192752.3       3296054     4051642
  Northern Ireland  |    1119091   44878.71       1031129     1207053
---------------------------------------------------------------------</code></pre>
</div>
</div>
<p>We can now amend the standard errors and CIs using the design factors from the LFS documentation. This has to be done by hand, by directly copying the relevant numbers from the LFS documentation.</p>
<p>For example, if we wanted to adjust the population estimates for London, we would need to start with the original standard error, multiply it by the relevanmt design effect, then compute the 95% confidence interval of the point estimate. The design effect for London is smaller than 1, which indicates that the confidence interval after correction will be narrower - more precise than when simple random sampling was assumed.</p>
<p>Here is the adjusted standard error for London:</p>
<div id="7bb9dc0a" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb35-1"><a href="#cb35-1"></a>dis 294956.8*0.9634</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. dis 294956.8*0.9634
284161.38</code></pre>
</div>
</div>
<p>… The corresponding lower bound of the confidence interval</p>
<div id="e0c06eae" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb37-1"><a href="#cb37-1"></a>dis 5912194-1.96*(294956.8*0.9634)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. dis 5912194-1.96*(294956.8*0.9634)
5355237.7</code></pre>
</div>
</div>
<p>… And the upper bound</p>
<div id="4753a412" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb39-1"><a href="#cb39-1"></a>dis 5912194+1.96*(294956.8*0.9634)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>. dis 5912194+1.96*(294956.8*0.9634)
6469150.3</code></pre>
</div>
</div>
<p>… Instead of the original one:</p>
<p><code>[5334080 -6490308]</code></p>
<p>We can see that it is indeed narrower.</p>
<p><em>Note</em>: it would be possible to produce an amended table in full, using Stata’s MATA functions.</p>
<div id="bd2813b5" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb41-1"><a href="#cb41-1"></a>mat input <span class="kw">deff</span>= (0.8712,1.0857,1.3655,1.0051,0.9634,1.0382,0.8936,1.3272,0.9677,0.9137, 1.0012,1.0437,0.7113)</span>
<span id="cb41-2"><a href="#cb41-2"></a></span>
<span id="cb41-3"><a href="#cb41-3"></a>mat orig= <span class="fu">e</span>(b)',<span class="fu">r</span>(<span class="kw">table</span>)[<span class="st">"se"</span>,.]',deff',<span class="fu">hadamard</span>(<span class="fu">r</span>(<span class="kw">table</span>)[<span class="st">"se"</span>,.],<span class="kw">deff</span>)'</span>
<span id="cb41-4"><a href="#cb41-4"></a></span>
<span id="cb41-5"><a href="#cb41-5"></a>*mat ciL = <span class="kw">test</span>[.,<span class="st">"total"</span>]-(1.96*tot<span class="ot">$SE</span>*tot<span class="ot">$deft</span>)</span>
<span id="cb41-6"><a href="#cb41-6"></a>*tot[<span class="st">"97.5%"</span>]&lt;-tot<span class="ot">$total</span>+(1.96*tot<span class="ot">$SE</span>*tot<span class="ot">$deft</span>)</span>
<span id="cb41-7"><a href="#cb41-7"></a>*<span class="ot">rownames</span>(tot)&lt;-<span class="fu">substr</span>(<span class="ot">rownames</span>(tot),10,nchar(<span class="ot">rownames</span>(tot)))</span>
<span id="cb41-8"><a href="#cb41-8"></a>*kable(<span class="fu">round</span>(tot[,c(<span class="st">"2.5%"</span>,<span class="st">"97.5%"</span>)]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
. mat input deff= (0.8712,1.0857,1.3655,1.0051,0.9634,1.0382,0.8936,1.3272,0.96
&gt; 77,0.9137, 1.0012,1.0437,0.7113)

. 
. mat orig= e(b)',r(table)["se",.]',deff',hadamard(r(table)["se",.],deff)'

. 
. *mat ciL = test[.,"total"]-(1.96*tot$SE*tot$deft)
. *tot["97.5%"]&lt;-tot$total+(1.96*tot$SE*tot$deft)
. *rownames(tot)&lt;-substr(rownames(tot),10,nchar(rownames(tot)))
. *kable(round(tot[,c("2.5%","97.5%")]))
. </code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Blair2014" class="csl-entry" role="listitem">
Blair, Johnny. 2014. <em>Designing Surveys : A Guide to Decisions and Procedures.</em> 3rd edition / Johnny Blair, Ronald F. Czaja, Edward A. Blair. Los Angeles: SAGE.
</div>
<div id="ref-DWP2014" class="csl-entry" role="listitem">
DWP. 2014. <span>“Uncertainty in Family Resources Survey-Based Analysis. Guidance on Estimating Uncertainty in Family Resources Survey-Based Analysis.”</span> Edited by Department for Work and Pensions. 2014. <a href="https://www.gov.uk/government/publications/uncertainty-in-family-resources-survey-based-analysis">https://www.gov.uk/government/publications/uncertainty-in-family-resources-survey-based-analysis</a>.
</div>
<div id="ref-IBM2020" class="csl-entry" role="listitem">
IBM Support. 2020. <span>“Inconsistency in the Output When Using Weighting Procedure. IBM Support Document Number 419449.”</span> 2020. <a href="https://www.ibm.com/support/pages/inconsistency-output-when-using-weighting-procedure">https://www.ibm.com/support/pages/inconsistency-output-when-using-weighting-procedure</a>.
</div>
<div id="ref-Kish1995" class="csl-entry" role="listitem">
Kish, Leslie. 1995. <em>Survey Sampling</em>. Wiley Classics Library. New York: Wiley.
</div>
<div id="ref-Lohr20192010" class="csl-entry" role="listitem">
Lohr, Sharon L. 2019 - 2010. <em>Sampling : Design and Analysis</em>. Second edition. Texts in Statistical Science. Boca Raton, FL: CRC Press.
</div>
<div id="ref-Lumley2023" class="csl-entry" role="listitem">
Lumley, Thomas. 2023. <span>“Survey: Analysis of Complex Survey Samples.”</span>
</div>
<div id="ref-ONS2022" class="csl-entry" role="listitem">
ONS. 2022. <span>“Family Resources Survey, 2020/21 Methodology and Standard Error Tables.”</span> Edited by Office for National Statistics. 2022. <a href="https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1065513/Ch1_Methodology_and_Standard_Errors.ods">https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1065513/Ch1_Methodology_and_Standard_Errors.ods</a>.
</div>
<div id="ref-Curran2016" class="csl-entry" role="listitem">
P, Curran. 2016. <span>“Complex Survey Designs and Weighting Using Stata: Part 1-3.”</span> 2016. <a href="https://www.youtube.com/watch?v=oOpJdC_oeKY">https://www.youtube.com/watch?v=oOpJdC_oeKY</a>.
</div>
<div id="ref-UKDS2018" class="csl-entry" role="listitem">
UKDS. 2018. <span>“Data Skills Modules: Applying Weights to Survey Data.”</span> Edited by UK Data Service. 2018. <a href="https://www.youtube.com/watch?v=TIad5__WP8g">https://www.youtube.com/watch?v=TIad5__WP8g</a>.
</div>
<div id="ref-UKDS2019" class="csl-entry" role="listitem">
———. 2019. <span>“Weights in Social Surveys: An Introduction:”</span> Edited by UK Data Service. 2019. <a href="https://www.youtube.com/watch?v=Vllr4olp3N4&amp;t=39s">https://www.youtube.com/watch?v=Vllr4olp3N4&amp;t=39s</a>.
</div>
<div id="ref-Wallrich2019" class="csl-entry" role="listitem">
Wallrich, Lukas. 2019. <span>“Week 7 Using Survey Weights in r.”</span> Edited by Goldsmiths Core Quantitative Methods Series. 2019. <a href="https://www.youtube.com/watch?v=brxx81U6N1o">https://www.youtube.com/watch?v=brxx81U6N1o</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./06_SPSS.html" class="pagination-link" aria-label="SPSS">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">SPSS</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09_References.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>